// GENERATED by player/scripts/generate-item-icons.mjs — do not edit by hand.
//
// The universal actions. Dodge is absent on purpose: BG3 has no such
// action, so it resolves to a generic glyph instead.

export const ACTION_ICONS: Record<string, string> = {
  'dash': '/icons/actions/dash.webp',
  'disengage': '/icons/actions/disengage.webp',
  'hide': '/icons/actions/hide.webp',
  'help': '/icons/actions/help.webp',
  'jump': '/icons/actions/jump.webp',
  'shove': '/icons/actions/shove.webp'
}
