// GENERATED by player/scripts/generate-item-icons.mjs — do not edit by hand.
//
// One representative icon per equipment category. Items are iconified by
// what KIND of thing they are, not by name: only 11% of SRD items have
// matching bg3.wiki art, because BG3 ships its own itemisation.

export const CATEGORY_ICONS: Record<string, string> = {
  'armor': '/icons/categories/armor.png',
  'shield': '/icons/categories/shield.png',
  'head': '/icons/categories/head.png',
  'cloak': '/icons/categories/cloak.png',
  'gloves': '/icons/categories/gloves.png',
  'boots': '/icons/categories/boots.png',
  'amulet': '/icons/categories/amulet.png',
  'ring': '/icons/categories/ring.png',
  'potion': '/icons/categories/potion.png',
  'scroll': '/icons/categories/scroll.png',
  'wand': '/icons/categories/wand.png',
  'instrument': '/icons/categories/instrument.png'
}
